using Content.Client.UserInterface.Controls;
using Content.Shared.DeadSpace.PdaPainter;
using Content.Shared.PDA;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.DeadSpace.PdaPainter.UI;

[GenerateTypedNameReferences]
public sealed partial class PdaPainterWindow : DefaultWindow
{
    private static readonly Color[] Palette =
    {
        Color.Red,
        Color.Orange,
        Color.Yellow,
        Color.Green,
        Color.Cyan,
        Color.Blue,
        Color.Purple,
        Color.White,
        Color.Black,
    };

    public event Action<List<int>, List<int>>? OnPixelsDrawn;
    public event Action<string?>? OnSavePressed;
    public event Action? OnResetPressed;

    [Dependency] private readonly IEntityManager _entMan = default!;
    [Dependency] private readonly IPrototypeManager _proto = default!;
    [Dependency] private readonly SharedAppearanceSystem _appearance = default!;

    private readonly SpriteSystem _spriteSystem;

    private Color _currentColor = Palette[0];
    private int _selectedPaletteIndex;
    private PdaPainterTool _tool = PdaPainterTool.Brush;
    private string? _selectedTemplate;
    private string? _previewProtoId;
    private readonly List<string> _templateIds = new();
    private readonly Dictionary<string, (string? Rsi, string? State)> _templateRsi = new();

    private readonly Dictionary<int, int> _pixels = new();
    private readonly Dictionary<int, Button> _paletteButtons = new();
    private bool _populated;

    public PdaPainterWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _spriteSystem = _entMan.System<SpriteSystem>();

        Tabs.SetTabTitle(0, Loc.GetString("pda-painter-tab-free"));
        Tabs.SetTabTitle(1, Loc.GetString("pda-painter-tab-template"));

        PopulatePalette();
        WireCanvas(FreeCanvas);
        WireCanvas(TemplateCanvas);

        ColorPicker.OnColorChanged += color =>
        {
            _currentColor = color;
            SelectPaletteIndex(-1);
        };

        BrushButton.OnPressed += _ => SelectTool(PdaPainterTool.Brush);
        EraserButton.OnPressed += _ => SelectTool(PdaPainterTool.Eraser);
        PipetteButton.OnPressed += _ => SelectTool(PdaPainterTool.Pipette);

        Size1Button.OnPressed += _ => SelectBrushSize(1);
        Size2Button.OnPressed += _ => SelectBrushSize(2);
        Size3Button.OnPressed += _ => SelectBrushSize(3);

        TemplateList.OnItemSelected += args =>
        {
            if (args.ItemIndex >= 0 && args.ItemIndex < _templateIds.Count)
                SelectTemplate(_templateIds[args.ItemIndex]);
        };

        SaveButton.OnPressed += _ =>
        {
            var templateId = Tabs.CurrentTab == 1 ? _selectedTemplate : null;
            OnSavePressed?.Invoke(templateId);
        };

        ResetButton.OnPressed += _ =>
        {
            _pixels.Clear();
            _selectedTemplate = null;
            UpdateTemplateHighlight();
            RefreshCanvases();
            OnResetPressed?.Invoke();
        };

        SelectTool(PdaPainterTool.Brush);
        SelectBrushSize(1);
    }

    public void UpdateState(PdaPainterBoundUserInterfaceState state)
    {
        _pixels.Clear();
        foreach (var (k, v) in state.Canvas)
        {
            _pixels[k] = v;
        }

        _previewProtoId = state.PreviewProtoId;

        PdaNameLabel.Text = state.PreviewName != null
            ? Loc.GetString("pda-painter-inserted", ("name", state.PreviewName))
            : Loc.GetString("pda-painter-no-pda");

        if (!_populated)
        {
            PopulateTemplates(state.Templates);
            _populated = true;
        }

        if (_selectedTemplate == null && state.SelectedTemplate != null)
            _selectedTemplate = state.SelectedTemplate;

        UpdateTemplateHighlight();
        RefreshCanvases();
    }

    private void PopulatePalette()
    {
        for (var i = 0; i < Palette.Length; i++)
        {
            var index = i;
            var button = new Button
            {
                MinHeight = 32,
            };
            button.StyleClasses.Add("pda-painter-swatch");
            // Show the color with both a background override and a label glyph.
            var swatch = new PanelContainer
            {
                HorizontalExpand = true,
                MinHeight = 32,
            };
            swatch.PanelOverride = new StyleBoxFlat(Palette[i]);
            button.AddChild(swatch);
            button.OnPressed += _ =>
            {
                _currentColor = Palette[index];
                SelectPaletteIndex(index);
            };
            PaletteGrid.AddChild(button);
            _paletteButtons[index] = button;
        }

        SelectPaletteIndex(0);
    }

    private void PopulateTemplates(List<PdaPainterTemplateInfo> templates)
    {
        TemplateList.Clear();
        _templateIds.Clear();

        foreach (var template in templates)
        {
            var (icon, rsi, spriteState) = ResolvePdaSprite(template.Id);
            _templateRsi[template.Id] = (rsi, spriteState);

            Texture? iconTexture = null;
            if (rsi != null && spriteState != null)
            {
                try
                {
                    iconTexture = _spriteSystem.Frame0(new SpriteSpecifier.Rsi(new ResPath(rsi), spriteState));
                }
                catch
                {
                    // Missing RSI/state: list the entry without an icon.
                }
            }

            TemplateList.AddItem(template.Name, iconTexture ?? icon, metadata: template.Id);
            _templateIds.Add(template.Id);
        }
    }

    /// <summary>
    /// Resolves the base sprite (icon texture, RSI path and state) of a PDA
    /// prototype by spawning a client-side copy of it in nullspace.
    /// </summary>
    private (Texture? icon, string? rsi, string? state) ResolvePdaSprite(string protoId)
    {
        if (!_proto.TryIndex<EntityPrototype>(protoId, out var proto) || proto.Abstract)
            return (null, null, null);

        EntityUid? ent = null;

        try
        {
            ent = _entMan.SpawnEntity(protoId, MapCoordinates.Nullspace);

            string? state = null;
            if (_appearance.TryGetData<string>(ent.Value, PdaVisuals.PdaType, out var initState))
                state = initState;

            string? rsi = null;
            if (_entMan.TryGetComponent<SpriteComponent>(ent, out var sprite))
            {
                rsi = sprite.BaseRSI?.Path.ToString();
            }

            Texture? icon = null;
            if (rsi != null && state != null)
            {
                try
                {
                    icon = _spriteSystem.Frame0(new SpriteSpecifier.Rsi(new ResPath(rsi), state));
                }
                catch
                {
                    // Missing RSI/state: no icon.
                }
            }

            return (icon, rsi, state);
        }
        catch
        {
            return (null, null, null);
        }
        finally
        {
            if (ent != null)
                _entMan.DeleteEntity(ent.Value);
        }
    }

    private void WireCanvas(PdaPainterCanvas canvas)
    {
        canvas.PixelsChanged += (indices, colors) => OnPixelsDrawn?.Invoke(indices, colors);
        canvas.PickedColor += color =>
        {
            _currentColor = color;
            SelectPaletteIndex(-1);
        };
    }

    private void SelectTool(PdaPainterTool tool)
    {
        _tool = tool;
        FreeCanvas.Tool = tool;
        TemplateCanvas.Tool = tool;
    }

    private void SelectBrushSize(int size)
    {
        FreeCanvas.BrushSize = size;
        TemplateCanvas.BrushSize = size;
    }

    private void SelectPaletteIndex(int index)
    {
        _selectedPaletteIndex = index;
        foreach (var (i, button) in _paletteButtons)
        {
            button.Pressed = i == index;
        }
    }

    private void SelectTemplate(string templateId)
    {
        _selectedTemplate = templateId;
        UpdateTemplateHighlight();
        RefreshCanvases();
    }

    private void UpdateTemplateHighlight()
    {
        for (var i = 0; i < _templateIds.Count; i++)
        {
            TemplateList[i].Selected = _templateIds[i] == _selectedTemplate;
        }
    }

    private void RefreshCanvases()
    {
        var freeBackdrop = LoadBackdrop(ResolvePdaSprite(_previewProtoId ?? "BasePDA"));
        FreeCanvas.Backdrop = freeBackdrop;

        var (tRsi, tState) = _selectedTemplate != null && _templateRsi.TryGetValue(_selectedTemplate, out var resolved)
            ? resolved
            : (null, null);
        var templateBackdrop = LoadBackdrop((null, tRsi, tState));
        TemplateCanvas.Backdrop = templateBackdrop;

        FreeCanvas.Pixels = _pixels;
        TemplateCanvas.Pixels = _pixels;
        FreeCanvas.ColorProvider = () => _currentColor;
        TemplateCanvas.ColorProvider = () => _currentColor;

        FreeCanvas.UpdateDraw();
        TemplateCanvas.UpdateDraw();
    }

    private Texture? LoadBackdrop((Texture?, string?, string?) resolved)
    {
        var (_, rsi, state) = resolved;
        if (rsi == null || state == null)
            return null;

        try
        {
            return _spriteSystem.Frame0(new SpriteSpecifier.Rsi(new ResPath(rsi), state));
        }
        catch
        {
            return null;
        }
    }
}
